In [23]:
import random
import numpy as np

# Primer Functions

### *

In [52]:
my_list = [1,2,3]
print(my_list)

[1, 2, 3]


In [53]:
print(*my_list)

1 2 3


### Random 

In [39]:
import random
random.random()

0.33844051243073625

In [38]:
# (b - a) * random_sample() + a
random.uniform(3,8)

7.772024014335885

In [24]:
np.random.random_sample()

0.11919402208670005

In [20]:
np.random.random_sample(4)

array([0.07384755, 0.9005251 , 0.30030561, 0.38221819])

In [22]:
np.random.random_sample([2,4])

array([[0.76851156, 0.56973309, 0.47074505, 0.7814957 ],
       [0.5778028 , 0.94653057, 0.51193493, 0.48693931]])

In [42]:
# (b - a) * random_sample() + a
a = 3; b = 8
(b-a)*np.random.random_sample([2,4])+a

array([[4.65799262, 6.32702018, 6.55545234, 5.45877784],
       [7.69941994, 4.68709357, 5.49790728, 4.60913966]])

### Round

In [43]:
np.round(np.random.random_sample([2,4]),2)

array([[0.76, 0.06, 0.41, 0.4 ],
       [0.07, 0.51, 0.84, 0.76]])

### range

In [58]:
print(range(5))
print(*range(5))
print(*range(3,8))

range(0, 5)
0 1 2 3 4
3 4 5 6 7


In [47]:
#range([start], stop[, step])

for i in range(3,8):
    print(i)

3
4
5
6
7
